### ISSUE TITLE
Update documentation about Smart Contract Rent with terminology and timeline

### ISSUE THREAD

**Issue by ed-marquez** [hiero-ledger/hiero-docs#174]
### Problem

https://docs.hedera.com/guides/core-concepts/smart-contracts/gas-and-fees#smart-contract-rent-and-auto-renewal
^This subsection does no longer reflect the latest timeline for enabling contract rent. 

See this issue: https://github.com/hashgraph/hedera-services/issues/4304

@theekrystallee @SimiHunjan  

### Solution

For the text below and based on changes in the issue linked above, we need to clarify if:
- the feature will be enabled with release 0.31 of Hedera services and the expiry occurs after 90 days
- OR if release 0.30 still applies but expiry occurs after 120

```
Smart contract entity auto renewal and expiry was introduced in the 0.30.4 Hedera Services release. All contract authors to are encouraged to set an auto-renew account for their contract.

All non-deleted contracts will have their expiry extended to at least 90 days after the 0.30.4 upgrade date

About 90 days after the 0.30.4 upgrade, some contracts will begin to expire. The network will try to automatically charge the renewal fee to the expired contract's auto-renew account. If an auto-renew account has zero balance, the network will then try to charge the contract itself.
```

Also, I believe this was 1000 for each contract instead 100:
`Each contract has 100 free key-value pairs of storage available`

**Comment by SimiHunjan** [comment]
hey @ed-marquez ! The expiry with the 90 day extension was enabled in the 0.30 release. What we are doing now is disabling the feature so that after the expiration period extension we will not be charging the auto renew fees immediately in January. If we enable the auto renew and expiration say March then it will take into effect then. Here is an example of the expected flow @tinker-michaelj provided:

- We re-enable contract expiration in, say, March
- A bunch of contracts still have expiration dates in January
- The expiration system task finds one of these expired contracts, 0.0.X, and tries to auto-renew it
- Since 0.0.X has a funded auto-renew account 0.0.A, the system is able to charge 0.0.A for 0.0.X's next 90 days (Note we will not charge any "catch-up" fees for February, even though the contract was technically expired.)
- The cycle continues.

**Comment by ed-marquez** [comment]
Thank you for the clarification, Simi! Perfect, the current information in docs still applies. 
**Do we think it would be good to add a note about the feature not being enabled immediately (90 days after v0.30)?**

**Comment by SimiHunjan** [comment]
I added a note to the smart contract fees section here https://docs.hedera.com/guides/core-concepts/smart-contracts/gas-and-fees#smart-contract-rent-and-auto-renewal
